### ISSUE TITLE
Security: Are you sure...

### ISSUE THREAD

**Issue by josf** [yorickvP/yori-nix#1]
that you want to leave your GPG secret keys on a public Github repo? 

(Don't want to pester you if for some reason this is a non-issue, but I couldn't not say anything.)

**Comment by yorickvP** [comment]
If you mean my .asc files, all of them are encrypted with my GPG private key, which should not be on the repo. (things starting with -----BEGIN PGP MESSAGE----- are encrypted). Correct me if I am wrong here.

I will document the encryption in a readme later because you are not the first person to ask about it.
Thanks for looking out, it's much appreciated :)

**Comment by josf** [comment]
OK, I understand better now. And I don't know enough about Nix OS to understand the deployment issues. Just stumbled onto this repo because I'm thinking about try nix on my laptop. So all is well that ends well :-)
